### ISSUE TITLE
more flexible kernel loading

### ISSUE THREAD

**Issue by haraldsteinlechner** [DaKup/PRo3D-Extensions#3]
currentl pck0010 is loaded per default - as suggested in discord we can improve here.

this issue is mainly here to reference the associated commit and make it a bit traceable

**Comment by DaKup** [comment]
You can manually specify the path via AddSpiceKernel(const char* pcSpiceKernelFile). You can call this function repeatedly to load additional kernels or define a meta-kernel file (will be provided by JR) which contains all kernels at once.
